In [1]:
import numpy as np

In [2]:
a = np.array([[[1, 3], [2, 3]]])

In [3]:
A

NameError: name 'A' is not defined

In [4]:
a

array([list([1, 3]), list([2, 3]), list([1])], dtype=object)

In [5]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [6]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [7]:
a

array([list([1, 3]), list([2, 3]), list([1])], dtype=object)

In [8]:
a = np.array([[1, 3], [2, 3], [1, ]])


In [9]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [10]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [11]:
a = np.array([[1, 3], [2, 3]])

In [12]:
a

array([list([1, 3]), list([2, 3]), list([1])], dtype=object)

In [13]:
a = np.array([[1, 3], [2, 3]])

In [14]:
a

array([[1, 3],
       [2, 3]])

In [15]:
a = np.array([[[1, 6], [2, 8]], [[3, 11], [3, 10]], [[1, 7]]])

In [16]:
a

array([[list([1, 6]), list([2, 8])],
       [list([3, 11]), list([3, 10])],
       [1, 7]], dtype=object)

In [17]:
a = np.array([[[1, 6], [2, 8]], [[3, 11], [3, 10]], [[1, 7]]])

In [18]:
a

array([list([[1, 6], [2, 8]]), list([[3, 11], [3, 10]]), list([[1, 7]])],
      dtype=object)

In [19]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [20]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [23]:
m = np.array([])

In [24]:
np.mean(a, axis = 0, out = m)

ValueError: operands could not be broadcast together with shapes (1,0) (5,2) 

In [25]:
np.mean(a, axis = 0, out = m)

ValueError: operands could not be broadcast together with shapes (1,0) (5,2) 

In [26]:
m = np.zeros(6,)

In [27]:
m

array([0., 0., 0., 0., 0., 0.])

In [28]:
m = np.zeros(2,)

In [29]:
m

array([0., 0.])

In [30]:
np.mean(a, axis = 0, out = m)

array([2. , 8.4])

In [31]:
f = a - ,

SyntaxError: invalid syntax (<ipython-input-31-a98469b8ee2b>, line 1)

In [32]:
f = a - m

In [33]:
f

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [34]:
a_centered = a - m

In [35]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [36]:
a_centered_sp = np.dot(a_centered)

TypeError: dot() missing 1 required positional argument: 'b'

In [37]:
a_centered_sp = np.matmul(a_centered, a_centered)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 2)

In [38]:
a_centered_sp = np.dot(a_centered, a_centered)

ValueError: shapes (5,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [43]:
p = a_centered[:,0]

In [44]:
p

array([-1.,  0.,  1.,  1., -1.])

In [45]:
o = a_centered[:,1]

In [42]:
a_centered_sp = np.dot(p, o)

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

NameError: name 'a_centered_sp' is not defined

In [48]:
a_centered_sp

NameError: name 'a_centered_sp' is not defined

In [49]:
a_centered_sp=np.dot(o,p)

a_centered_sp

8.0

In [50]:
a_centered_sp

8.0

In [51]:
a_centered_sp

8.0

In [52]:
a_centered_sp = np.dot(p, o)

In [53]:
a_centered_sp

8.0

In [56]:
n = np.count_nonzero(a_centered, axis=1)

In [57]:
n

array([2, 1, 2, 2, 2], dtype=int64)

In [61]:
a_centered_sp2

array([3., 7., 3., 3., 3.])

In [62]:
n = 5

In [63]:
a_centered_sp2 = a_centered_sp // ( n - 1)

In [64]:
a_centered_sp2

0.0

In [65]:
a_centered_sp2 = a_centered_sp // ( n - 1)

In [66]:
a_centered_sp2

2.0